export const equipmentProfile = {
  dripper: "HARIO V60 02",
  grinder: "Comandante C40",
  filters: "CAFEC Abaca 02",
  tastePreference: "clean_bright",
};

export const analyzedBean = {
  name: "Las Flores Gesha",
  roaster: "Northbound Coffee",
  farm: "Las Flores",
  origin: "Huila, Colombia",
  variety: "Gesha",
  process: "Washed",
  roastLevel: "Light",
  flavorFocus: "Jasmine, citrus, honey",
  roastDate: "2026-03-18",
};

export const seedBrews = [
  {
    id: "seed-1",
    createdAt: "2026-03-21T09:00:00.000Z",
    date: "Mar 21",
    bean: "Yirgacheffe Chelbesa",
    roaster: "Northbound Coffee",
    farm: "Chelbesa",
    origin: "Yirgacheffe, Ethiopia",
    variety: "74110",
    process: "Washed",
    roastLevel: "Light",
    roastDate: "2026-03-16",
    dripper: "Origami Air S",
    ratio: "1:16.2",
    temp: "92C",
    grind: "Comandante C40: 23 clicks",
    pours: "Bloom 50g 0:00-0:35",
    rating: 4.5,
    note: "White peach, bright and silky.",
    source: "manual",
  },
  {
    id: "seed-2",
    createdAt: "2026-03-20T09:00:00.000Z",
    date: "Mar 20",
    bean: "Las Flores Gesha",
    roaster: "Northbound Coffee",
    farm: "Las Flores",
    origin: "Huila, Colombia",
    variety: "Gesha",
    process: "Washed",
    roastLevel: "Light",
    roastDate: "2026-03-18",
    dripper: "V60",
    ratio: "1:16",
    temp: "93C",
    grind: "Comandante C40: 22-24 clicks",
    pours: "Bloom 45g 0:00-0:35",
    rating: 4.8,
    note: "Jasmine lift, clean finish.",
    source: "manual",
  },
  {
    id: "seed-3",
    createdAt: "2026-03-18T09:00:00.000Z",
    date: "Mar 18",
    bean: "Shakisso Natural",
    roaster: "Northbound Coffee",
    farm: "Shakisso",
    origin: "Guji, Ethiopia",
    variety: "Heirloom",
    process: "Natural",
    roastLevel: "Medium",
    roastDate: "2026-03-14",
    dripper: "Kalita Wave",
    ratio: "1:15.2",
    temp: "91C",
    grind: "1Zpresso ZP6: 4.8-5.2",
    pours: "Bloom 50g 0:00-0:35",
    rating: 4.2,
    note: "Jammy, fuller body, low bitterness.",
    source: "manual",
  },
];
